title: Material
description: A Peco theme
author: Riko
email: rsakurauchi@madisoncollege.edu
feed: true
url: https://peco-theme-material.netlify.com
theme: ../
permalink: :slug
themeConfig:
  theme_color: "#0097A7"
  theme_sub_color: "#00838F"
  hyperlink_color: "#00838F"
  button_color: "#757575"
  android_chrome_color: "#0097A7"
  nprogress_color: "#29d"
  nprogress_buffer: "800"
  avatar: /img/avatar.jpeg
  sidebar_header: /img/sidebar_header.png
